version: "3.7"

services:
  localstack:
    image: localstack/localstack@sha256:9aca45322de052eba67631b8d65fe5c2838fb6ff7bf84cc12c66a556e68a7084 # 3.3.0
    volumes:
      - "/private${TMPDIR}/localstack:/var/lib/localstack"
      # - "./localstack:/docker-entrypoint-initaws.d"
      # - "./localstack:/etc/localstack/init/ready.d" # for intel chip Mac
    healthcheck:
      test: awslocal dynamodb list-tables
      interval: 60s
      timeout: 10s
    environment:
      - SERVICES=dynamodb
      - EAGER_SERVICE_LOADING=1  
    ports:
      - "4566:4566"
      #- "4510-4559:4510-4559"
